# -*- coding: utf-8 -*-
"""Task-4(Location-based Analysis).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gg1badWfkh0u18XqAYA9ig5LFHzIXcDa

**Importing libraries**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import folium

"""**Loading Data**"""

df=pd.read_csv("/content/Dataset .csv")
df.head()

df[['Latitude', 'Longitude']] = df[['Latitude', 'Longitude']].fillna(method='ffill')
df = df.dropna(subset=['City'])

map_center = [df['Latitude'].mean(), df['Longitude'].mean()]
restaurant_map = folium.Map(location=map_center, zoom_start=5)
for i, row in df.iterrows():
    folium.CircleMarker(
        location=[row['Latitude'], row['Longitude']],
        radius=2,
        popup=row['Restaurant Name'],
        color='blue',
        fill=True
    ).add_to(restaurant_map)
restaurant_map.save("restaurant_map.html")

city_counts = df['City'].value_counts().head(10)
plt.figure(figsize=(10, 5))
sns.barplot(x=city_counts.index, y=city_counts.values, palette='viridis')
plt.title('Top 10 Cities with Most Restaurants')
plt.ylabel('Number of Restaurants')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

city_avg_rating = df.groupby('City')['Aggregate rating'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10, 5))
sns.barplot(x=city_avg_rating.index, y=city_avg_rating.values, palette='coolwarm')
plt.title('Top 10 Cities by Average Restaurant Rating')
plt.ylabel('Average Rating')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

